### ISSUE TITLE
tuple or dict expected

### ISSUE THREAD

**Issue by kolserdav** [fixie-ai/fixie-sdk#122]
I started the agent on the local server with the `fixie agent serve` command. 
Then I try to make a request to it like this:
```sh
curl -X POST -H "Authorization: Bearer [TOKEN]" -d '{"message":{"text":"time"}}' http://localhost:8181/func
``` 
I get this response: 
```json
{"detail":[{"loc":["body"],"msg":"instance of AgentQuery, tuple or dict expected","type":"type_error.dataclass","ctx":{"class_name":"AgentQuery"}}]}
```

I think that most likely I am doing something wrong, tell me please ...

**Comment by juberti** [comment]
Hmm, that looks like it should work. @petersalas any ideas?

**Comment by petersalas** [comment]
@kolserdav does it work if you add `-H 'Content-Type: application/json'`?

**Comment by kolserdav** [comment]
> @kolserdav does it work if you add `-H 'Content-Type: application/json'`?

Thank you, it works
