### ISSUE TITLE
Error Not authenticated

### ISSUE THREAD

**Issue by diegoenriquesantos** [fixie-ai/fixie-sdk#155]
When I execute the following command:
fixie agent serve

The server started:

![fixie-agent-serve](https://user-images.githubusercontent.com/10709020/232884369-a1b56127-f6ba-4c61-9494-8c98fadcc7c4.JPG)

but the following error occur:

![Not-authenticated](https://user-images.githubusercontent.com/10709020/232884475-44132400-d062-4339-b836-85aae31bbdc5.JPG)

I was authenticated with my user linanayail.

**Comment by petersalas** [comment]
Hi @diegoenriquesantos, thank for the report! After running `fixie agent serve`, you should be able to interact with your agent on https://app.fixie.ai. (The URL reported in the terminal is how Fixie reaches your agent.)

I'll make the experience less confusing here.

**Comment by diegoenriquesantos** [comment]
Thanks @petersalas !
